version: "3.9"

services:
  dev:
    build: .
    image: feature-toggle-poc:latest
    environment:
      CONFIG_FILE: /app/config/dev.yaml

  qa:
    image: feature-toggle-poc:latest
    environment:
      CONFIG_FILE: /app/config/qa.yaml

  prod:
    image: feature-toggle-poc:latest
    environment:
      CONFIG_FILE: /app/config/prod.yaml
